default: &default
  adapter: postgresql
  encoding: unicode
  database: tastify
  username: postgres
  password: 1321
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: tastify_test
